FROM public.ecr.aws/x9d4j8f0/openmrs-qa-frontend@sha256:a36bcc775dd88e93fcd9ae58a941238b4348296ec3e27e2c4e90d8e2e69f690a
COPY reports-dist/ /usr/share/nginx/html/patched/openmrs-esm-reports-app-4.4.0-reports-flows-e1872d6430a9/
COPY importmap.json /usr/share/nginx/html/importmap.json
