import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const out=path.resolve((process.env.REPORTS_EVIDENCE||'test-results/objects')), ids=JSON.parse(fs.readFileSync(out+'/ref-ids.json')), expected=JSON.parse(fs.readFileSync(out+'/expected.json'));
const base='/openmrs/module/reporting',parent='org.openmrs.module.reporting.dataset.definition.DataSetDefinition',prefix='QA Reports Fix R3 20261008';
const results=[],events=[];
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({baseURL:'http://localhost:8090',httpCredentials:{username:'admin',password:'Admin123'},timezoneId:'UTC',viewport:{width:1550,height:1100}});
const p=await context.newPage();p.setDefaultTimeout(15000);p.on('dialog',d=>d.accept());p.on('pageerror',e=>events.push({type:'pageerror',message:e.message}));p.on('response',r=>{if(r.status()>=400)events.push({type:'http',url:r.url(),status:r.status()});});
const persist=()=>fs.writeFileSync(out+'/ref-ids.json',JSON.stringify(ids,null,2));
const route=(key,kind)=>base+'/definition/editAnnotatedDefinition.form?type=org.openmrs.module.reporting.dataset.definition.'+kind+'DataSetDefinition&parentType='+parent+'&uuid='+ids[key];
async function save(){await Promise.all([p.waitForURL('**/manageDefinitions.form?**'),p.locator('#save-button').click()]);}
async function record(name,fn){if(process.env.CASE&&!name.includes(process.env.CASE))return;const row={name};try{row.detail=await fn();row.status='pass';}catch(e){row.status='fail';row.error=e.message;}await p.screenshot({path:out+'/'+name+'.png',fullPage:true});fs.writeFileSync(out+'/'+name+'.html',await p.content());fs.writeFileSync(out+'/'+name+'.aria.yml',await p.locator('body').ariaSnapshot());results.push(row);fs.writeFileSync(out+'/browser-results.json',JSON.stringify({results,events},null,2));console.log(row.status,name,row.error?.slice(0,350)||'');}
const rows=()=>p.locator('#object-editor-columnDefinitions > fieldset');
async function addColumn(name,uuid){await p.getByRole('button',{name:'Add column',exact:true}).click();const row=rows().last();await row.getByLabel('Column name',{exact:true}).fill(name);await row.getByLabel('Data definition',{exact:true}).selectOption(uuid);return row;}
async function run(key){await p.goto(base+'/run/runReport.form?reportId='+ids[key+'Report']);const select=p.locator('[name=selectedRenderer]'),value=await select.locator('option').evaluateAll((xs,id)=>xs.find(x=>x.value.includes(id))?.value,ids[key+'Csv']);await select.selectOption(value);await p.locator('input[value="Request Report"]').click();await p.waitForURL('**/reportHistoryOpen.form?**');const uuid=new URL(p.url()).searchParams.get('uuid');ids.requests=[...new Set([...(ids.requests||[]),uuid])];persist();let data;await expect.poll(async()=>{data=await(await context.request.get('/openmrs/ws/rest/v1/reportingrest/reportRequest/'+uuid+'?v=full')).json();return data.status;},{timeout:90000,intervals:[1000,2000]}).toBe('COMPLETED');const response=await context.request.get(base+'/reports/viewReport.form?uuid='+uuid),csv=await response.text();fs.writeFileSync(out+'/'+key+'.csv',csv);return{uuid,csv};}
await p.goto('/openmrs/login.htm');await p.locator('#username').fill('admin');await p.locator('#password').fill('Admin123');await p.locator('input[type=submit]').click();
for(const [key,kind]of[['obs','Obs'],['visit','Visit'],['encounter','EncounterAndObs']]){
 await record(key+'-columns-sort-filter-save-reload',async()=>{
  const url=route(key,kind);await p.goto(url);await expect(p.locator('#object-editor-columnDefinitions')).toBeAttached();
  for(const field of['columnDefinitions','sortCriteria','rowFilters'])await p.locator('#selectValue'+field).selectOption('f');
  while(await rows().count())await rows().first().getByRole('button',{name:'Remove column',exact:true}).click();
  while(await p.getByRole('button',{name:'Remove row filter',exact:true}).count())await p.getByRole('button',{name:'Remove row filter',exact:true}).first().click();
  while(await p.getByRole('button',{name:'Remove sort rule',exact:true}).count())await p.getByRole('button',{name:'Remove sort rule',exact:true}).first().click();
  await addColumn('Object ID',ids[key+'Id']);const age=await addColumn('Age',ids.age);await age.getByLabel('Age effective date',{exact:true}).fill('09/29/2026');
  await age.getByLabel('Converter type',{exact:true}).selectOption('AgeConverter');await age.getByRole('button',{name:'Add converter',exact:true}).click();
  const gender=await addColumn('Gender',ids.gender);await gender.getByLabel('Converter type',{exact:true}).selectOption('StringConverter');await gender.getByRole('button',{name:'Add converter',exact:true}).click();await gender.getByLabel('conversions (JSON)',{exact:true}).fill('{"M":"Male","F":"Female"}');
  await gender.getByRole('button',{name:'Move up',exact:true}).click();await expect(rows().nth(1).getByLabel('Column name',{exact:true})).toHaveValue('Gender');
  await p.getByRole('button',{name:'Add sort rule',exact:true}).click();await p.getByLabel('Sort column',{exact:true}).last().selectOption('Object ID');await p.getByLabel('Direction',{exact:true}).last().selectOption('DESC');
  await p.getByRole('button',{name:'Add row filter',exact:true}).click();await p.getByLabel('Row filter definition',{exact:true}).last().selectOption(ids[key+'Filter']);
  await p.screenshot({path:out+'/'+key+'-configured-before-save.png',fullPage:true});
  await save();await p.goto(url);await expect(rows().nth(0).getByLabel('Column name',{exact:true})).toHaveValue('Object ID');await expect(rows().nth(1).getByLabel('Column name',{exact:true})).toHaveValue('Gender');await expect(rows().nth(2).getByLabel('Age effective date',{exact:true})).toHaveValue('09/29/2026');await expect(p.getByLabel('Direction',{exact:true}).last()).toHaveValue('DESC');await expect(p.getByLabel('Row filter definition',{exact:true}).last()).toHaveValue(ids[key+'Filter']);
  await save();await p.goto(url);await expect(rows().nth(2).getByLabel('Age effective date',{exact:true})).toHaveValue('09/29/2026');
  const config=JSON.parse(await p.locator('#object-editor-data').inputValue());fs.writeFileSync(out+'/'+key+'-config.json',JSON.stringify(config,null,2));return{columns:config.columns,sorts:config.sorts,filters:config.filters};
 });
 await record(key+'-bounded-report-download',async()=>{const result=await run(key);const lines=result.csv.trim().split(/\r?\n/);expect(lines[0]).toBe('"Object ID","Gender","Age"');expect(lines.length).toBeGreaterThan(1);expect(result.csv).toMatch(/Female|Male/);const actual=lines.slice(1).map(x=>Number(x.split(',')[0].replaceAll('"','')));expect(actual).toEqual([...actual].sort((a,b)=>b-a));if(key!=='encounter')expect(actual).toEqual(expected[key].map(Number).sort((a,b)=>b-a));else expect(actual.every(x=>expected[key].includes(String(x)))).toBe(true);return result;});
 await record(key+'-rename-remove-cancel-keyboard',async()=>{
  const url=route(key,kind);await p.goto(url);await rows().first().getByLabel('Column name',{exact:true}).fill('Record ID');await expect(p.getByLabel('Sort column',{exact:true}).last()).toHaveValue('Record ID');await rows().nth(2).getByRole('button',{name:'Remove column',exact:true}).click();await p.getByRole('button',{name:'Remove row filter',exact:true}).last().click();
  await save();await p.goto(url);await expect(rows()).toHaveCount(2);await expect(p.getByLabel('Row filter definition',{exact:true})).toHaveCount(0);await expect(p.getByLabel('Sort column',{exact:true}).last()).toHaveValue('Record ID');
  const add=p.getByRole('button',{name:'Add column',exact:true});await add.focus();await p.keyboard.press('Enter');await expect(rows()).toHaveCount(3);await rows().last().getByLabel('Column name',{exact:true}).fill('Cancelled column');await p.locator('#cancel-button').click();await p.goto(url);await expect(rows()).toHaveCount(2);await expect(p.locator('body')).not.toContainText('Cancelled column');return{keyboard:'Focused Add column + Enter',savedColumns:2};
 });
}
await record('duplicate-column-invalid-date-preserves-saved',async()=>{const url=route('obs','Obs');await p.goto(url);await rows().nth(1).getByLabel('Column name',{exact:true}).fill('Record ID');const response=await Promise.all([p.waitForResponse(r=>r.url().includes('saveAnnotatedDefinition.form')&&r.request().method()==='POST'),p.locator('#save-button').click()]);expect(response[0].status()).toBe(400);await expect(p.locator('body')).toContainText('Column names must be nonempty and unique');await p.goto(url);await expect(rows().nth(1).getByLabel('Column name',{exact:true})).toHaveValue('Gender');const age=await addColumn('Age invalid',ids.age);await age.getByLabel('Age effective date',{exact:true}).fill('not-a-date');const invalid=await Promise.all([p.waitForResponse(r=>r.url().includes('saveAnnotatedDefinition.form')&&r.request().method()==='POST'),p.locator('#save-button').click()]);expect(invalid[0].status()).toBe(400);await expect(p.locator('body')).toContainText('Invalid');await p.goto(url);await expect(rows()).toHaveCount(2);return{duplicate:400,invalidDate:400};});
await browser.close();if(results.some(x=>x.status!=='pass'))process.exitCode=1;
