import { chromium, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const out=path.resolve('test-results/editors'), ids=JSON.parse(fs.readFileSync(out+'/ref-ids.json'));
const base='/openmrs/module/reporting', results=[], events=[];
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({baseURL:'http://localhost:8090',httpCredentials:{username:'admin',password:'Admin123'},timezoneId:'UTC',viewport:{width:1440,height:1000}});
const p=await context.newPage(); p.on('response',async r=>{if(r.request().method()==='POST')fs.appendFileSync(out+'/posts.ndjson',JSON.stringify({url:r.url(),status:r.status(),body:await r.text().catch(()=>''),data:r.request().postData()?.replace(/OWASP-CSRFTOKEN=[^&]+/g,'OWASP-CSRFTOKEN=REDACTED')})+'\n');}); p.setDefaultTimeout(12000); p.on('dialog',d=>d.accept());
p.on('pageerror',e=>events.push({type:'pageerror',message:e.message})); p.on('response',r=>{if(r.status()>=400)events.push({type:'http',url:r.url(),status:r.status()});});
const frame=()=>p.frameLocator('iframe').last();
const idle=()=>p.waitForLoadState('networkidle',{timeout:2000}).catch(()=>{});
async function check(name,fn){if(process.env.CASE&&!name.includes(process.env.CASE))return;const row={name};try{row.detail=await fn();row.status='pass';}catch(e){row.status='fail';row.error=e.message;}for(const [i,f] of p.frames().entries())fs.writeFileSync(out+'/'+name+'-frame'+i+'.html',await f.content());await p.screenshot({path:out+'/'+name+'.png',fullPage:true});fs.writeFileSync(out+'/'+name+'.aria.yml',await p.locator('body').ariaSnapshot());results.push(row);fs.writeFileSync(out+'/browser-results.json',JSON.stringify({results,events},null,2));console.log(row.status,name,row.error?.slice(0,250)||'');}
async function preview(uuid){await p.goto(base+'/definition/manageDefinitions.form?type=org.openmrs.module.reporting.dataset.definition.DataSetDefinition');const row=p.locator('tr').filter({has:p.locator('a[href*="'+uuid+'"]')}).last();await row.locator('img[src*="play"]').click();await expect(frame().locator('body')).toContainText(/Evaluation Result|Unable|Error/);const text=await frame().locator('body').innerText();expect(text).not.toMatch(/Unable|Exception|Internal Error/);return text;}
await p.goto('/openmrs/login.htm');await p.locator('#username').fill('admin');await p.locator('#password').fill('Admin123');await p.locator('input[type=submit]').click();
await check('B02-indicator-add-reload-evaluate',async()=>{await p.goto(base+'/datasets/cohortIndicatorAndDimensionDatasetEditor.form?uuid='+ids.indicatorDataset);await p.getByText('[+] Add Indicator',{exact:true}).click();await frame().locator('[name=indicator]').selectOption(ids.indicator);await idle();await frame().locator('[name=indicatorNumber]').fill('1');await frame().locator('[name=label]').fill('One patient count');await Promise.all([p.waitForResponse(r=>r.url().includes('cohortIndicatorAndDimensionAddSpecification.form')&&r.request().method()==='POST'),frame().getByRole('button',{name:'Submit',exact:true}).click()]);await idle();await p.reload();await expect(p.locator('body')).toContainText('One patient count');const text=await preview(ids.indicatorDataset);expect(text.split('Evaluation Result')[1]).toMatch(/\b1\b/);return text;});
await check('B03-iterations-add-edit-reload-evaluate',async()=>{await p.goto(base+'/datasets/multiParameterDataSetEditor.form?uuid='+ids.multi);await p.locator('#baseDefinitionSelect').selectOption(ids.sql);await idle();await p.reload();for(let n=0;n<2;n++){await p.getByText('[+] Add Iteration',{exact:true}).click();await idle();await p.reload();await p.locator('#iterations-table img[src*="edit"]').nth(n).click();await frame().locator('[name=fixedValue]').fill(String(n+7));await frame().getByRole('button',{name:'Submit',exact:true}).click();await idle();await p.reload();}const text=await preview(ids.multi);expect(text.split('Evaluation Result')[1]).toMatch(/\b7\b/);expect(text.split('Evaluation Result')[1]).toMatch(/\b8\b/);return text;});
await check('C3-patient-filter-roundtrip',async()=>{const route=base+'/datasets/patientDataSetEditor.form?uuid='+ids.patientDataset;await p.goto(route);await p.locator('input[name=label]').fill('Gender');await p.locator('#addCol .changeButton').click();await frame().locator('#valueUuid').selectOption(ids.gender);await frame().getByRole('button',{name:'Use this mapped value',exact:true}).click();await p.locator('#add-column-form input[type=submit]').click();await idle();await p.locator('#addFilterButton').click();await frame().locator('#valueUuid').selectOption(ids.cohort);await frame().getByRole('button',{name:'Use this mapped value',exact:true}).click();await idle();await p.locator('#unsaved input[type=submit][value=Save]').click();await idle();await p.goto(route);await expect(p.locator('body')).toContainText('QA Reports Fix R2 20261008-cohort');const text=await preview(ids.patientDataset);expect(text.split('Evaluation Result')[1]).toMatch(/\b[MF]\b/);return text;});
await check('A05-mapped-cohort-run-download',async()=>{
 await p.goto(base+'/run/runReport.form?reportId='+ids.report);await p.locator('#baseCohort .changeButton').click();await frame().locator('#valueUuid').selectOption(ids.cohort);await frame().getByRole('button',{name:'Use this mapped value',exact:true}).click();
 const select=p.locator('[name=selectedRenderer]');const option=await select.locator('option').evaluateAll((xs,id)=>xs.find(x=>x.value.includes(id))?.value,ids.csv);await select.selectOption(option);await p.locator('input[type=submit][value="Request Report"]').click();await p.waitForURL('**/reportHistoryOpen.form?**');const uuid=new URL(p.url()).searchParams.get('uuid');ids.requests=[...new Set([...(ids.requests||[]),uuid])];fs.writeFileSync(out+'/ref-ids.json',JSON.stringify(ids,null,2));
 const endpoint='/openmrs/ws/rest/v1/reportingrest/reportRequest/'+uuid+'?v=full';await expect.poll(async()=>{const r=await context.request.get(endpoint);return(await r.json()).status;},{timeout:90000,intervals:[500,1000]}).toBe('COMPLETED');const response=await context.request.get(base+'/reports/viewReport.form?uuid='+uuid);const csv=await response.text();expect(csv.trim().split('\n')).toHaveLength(2);expect(csv).toContain('Gender');expect(csv).toMatch(/"[MF]"/);fs.writeFileSync(out+'/mapped-cohort.csv',csv);return {uuid,csv};
});
await check('B05-static-query-create-rename-delete',async()=>{
 const type='org.openmrs.module.reporting.cohort.definition.StaticCohortDefinition',parent='org.openmrs.module.reporting.cohort.definition.CohortDefinition',name='QA Reports Fix R2 20261008 Static query';
 const route=base+'/definition/editAnnotatedDefinition.form?type='+type+'&parentType='+parent;
 await p.goto(route+'&uuid=');await p.locator('#name').fill(name);await p.locator('#selectValuecohort').selectOption('f');await p.locator('#cohort').selectOption({label:'Antenatal care'});await p.locator('#save-button').click();await idle();
 const row=p.locator('tr').filter({has:p.getByText(name,{exact:true})}).last();const href=await row.locator('a[href*="editDefinition.form"]').getAttribute('href');ids.staticQuery=new URL(href,'http://localhost:8090/openmrs/module/reporting/definition/').searchParams.get('uuid');fs.writeFileSync(out+'/ref-ids.json',JSON.stringify(ids,null,2));
 await p.goto(route+'&uuid='+ids.staticQuery);await expect(p.locator('#name')).toHaveValue(name);await expect(p.locator('#cohort option:checked')).toHaveText(/Antenatal care/);await p.locator('#name').fill(name+' renamed');await p.locator('#save-button').click();await idle();await p.goto(route+'&uuid='+ids.staticQuery);await expect(p.locator('#name')).toHaveValue(name+' renamed');
 await p.goto(base+'/definition/purgeDefinition.form?uuid='+ids.staticQuery+'&type='+type);await p.goto(base+'/definition/manageDefinitions.form?type='+parent);await expect(p.locator('body')).not.toContainText(name+' renamed');return {uuid:ids.staticQuery,clinicalCohort:'Antenatal care',clinicalInvariant:'Compared separately by cohort-snapshot.py'};
});
await browser.close();if(results.some(x=>x.status!=='pass'))process.exitCode=1;
